Ruby on Rails capstone project - Budget app
ogagaoghene/budget_app pull request #2
Opened 2022-12-01 17:25 UTC by ogagaoghene

# Ruby on Rails capstone project - Budget app

## Desciption
A mobile web application where you can manage your budget. You have a list of transactions associated with a category, so that you can see how much money you have spent and on what. It allows:
- Sign up and Sign for authentication
- Introduces new transactions associated with a category.
- It shows the money spent on each category.

2022-12-01 23:07 UTC, DammyShittu requested changes
Hi @ogagaoghene,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 23:07 UTC, DammyShittu commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] In this acknowledgment section of the README kindly gives appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2022-12-01 23:07 UTC, DammyShittu commented on app/views/categories/index.html.erb
> +  <% unless @categories.empty? %>
- [ ] I get this error immediately after signing in to the app.

  ![tutip](https://user-images.githubusercontent.com/54848363/205174267-c522f226-628c-40a4-bea9-43e61bfb9fdb.jpg)

  In your index action in the CategoriesController, you have this code `current_user.categories`, but there is no such thing as a `user_id` in the categories (from your schema). Kindly fix that.

  ```
  create_table "categories", force: :cascade do |t|
    t.string "name"
    t.string "icon"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
  ```

2022-12-01 23:07 UTC, DammyShittu commented on app/controllers/categories_controller.rb
> +    category.author_id = current_user.id
- [ ] I cannot create a category. Kindly fix this error as well after adding `user_id` to the categories table as highlighted above. Remember to use `user_id` or `author_id` depending on your migration.

  ![titoe](https://user-images.githubusercontent.com/54848363/205175825-79daff5e-43d9-4c93-88a8-2c0c93f9bdc5.jpg)

2022-12-01 23:07 UTC, DammyShittu commented on app/controllers/payments_controller.rb
> +    @category_payment = @payment.category_payments.build
- [ ] When I visit the page to create a payment, I get the error below. I am unable to create a payment. Kindly fix that.

  ![rirro](https://user-images.githubusercontent.com/54848363/205176504-90542327-2b60-4188-9e49-6c39b63aedd9.jpg)

  The `categories_payments` currently does not have `category_id` and `payment_id`. Kindly run migrations to add them since the table serves as a middle table in the many-to-many relationship between both models, so it should belong to the payment and category.

  ```
  create_table "category_payments", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
  ```

2022-12-01 23:07 UTC, DammyShittu commented on db/migrate/20221130204826_create_payments.rb
> +end
- [ ] Based on the schema shared with you, a payment should belong to an author. So that means there should be an `author_id` in the Payment table. Kindly run the necessary migration to reference an author through the User table.

  Here is a clue: [https://stackoverflow.com/questions/13694654/specifying-column-name-in-a-references-migration](https://stackoverflow.com/questions/13694654/specifying-column-name-in-a-references-migration)

  ```
  create_table "payments", force: :cascade do |t|
    t.string "name"
    t.string "amount"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
  ```

2022-12-01 23:07 UTC, DammyShittu commented on spec/views/login_spec.rb
> +end
- [ ] Good adding integration spec login action. Kindly add more integration tests covering important features in the app, like creating a category, payment, and so on.

2022-12-01 23:07 UTC, DammyShittu commented on README.md
> +- [Shared Video Link](https://www.loom.com/share/2e354b12e0dc4179ae0b0232bb22fad8)👈
- [ ] Your video presentation should not be longer than 5 minutes - yours is almost 7 minutes. Kindly re-record your video and ensure it does not exceed 5 minutes and please remember to highlight the piece of code you find interesting or are proud of.

2022-12-01 23:19 UTC, ogagaoghene commented
@DammyShittu Okay thanks. I will try to fix those issues.

2022-12-02 20:36 UTC, ogagaoghene commented
@DammyShittu  Thanks for your professional code review. Thanks for the tips. I have done what you requested of me. I would appreciate a positive feedback because I have already repeated a block. Thanks in anticipation

2022-12-02 20:45 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 20:59 UTC, ogagaoghene commented
@CollinsTatang Thanks bro. I appreciate you guys. Thanks for the good work you guys are doing. I am proud of you guys. Many thanks

2022-12-02 20:59 UTC, merged